services:
  app:
    image: 'jc21/nginx-proxy-manager:2.12.3'
    container_name: nginx-pm-app
    restart: unless-stopped
    networks:
      - nginx-backend
      - nginx-frontend
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: 'db'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER__FILE: /secrets/mysql_user
      DB_MYSQL_PASSWORD__FILE: /secrets/mysql_pass
      DB_MYSQL_NAME__FILE: /secrets/mysql_db
    volumes:
      - /custom/path/to/storage/nginx-pm/data:/data
      - /custom/path/to/storage/nginx-pm/letsencrypt:/etc/letsencrypt
      - ./mysql_db:/secrets/mysql_db
      - ./mysql_user:/secrets/mysql_user
      - ./mysql_pass:/secrets/mysql_pass
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:10.11.5'
    container_name: nginx-pm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD__FILE: /secrets/mysql_root_pass
      MYSQL_DATABASE__FILE: /secrets/mysql_db
      MYSQL_USER__FILE: /secrets/mysql_user
      MYSQL_PASSWORD__FILE: /secrets/mysql_pass
      MARIADB_AUTO_UPGRADE: '1'
    networks:
      - nginx-backend
    volumes:
      - /custom/path/to/storage/nginx-pm/mysql:/var/lib/mysql
      - ./mysql_root_pass:/secrets/mysql_root_pass
      - ./mysql_db:/secrets/mysql_db
      - ./mysql_user:/secrets/mysql_user
      - ./mysql_pass:/secrets/mysql_pass

networks:
  nginx-backend:
    name: nginx-backend
  nginx-frontend:
    name: nginx-frontend
