services:
  ddclient:
    image: linuxserver/ddclient:4.0.0
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /custom/path/to/storage/ddclient/config:/config
    restart: unless-stopped
